#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e "===\n>> Pre-push Hook: Checking branch name ..."

BRANCH=$(git rev-parse --abbrev-ref HEAD)
PROTECTED_BRANCHES="^(master|main|staging|develop|production)"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]; then
  echo -e "\n🚫 Cannot push to remote $BRANCH branch, please create your own branch and use PR/ Pull Request." && exit 1
fi

echo -e ">> Finish checking branch name \n==="

yarn lint-staged && yarn test

exit 0
